name: Push to Test Branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  push-to-test-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.ref }}
          fetch-depth: 0
      - name: Push changes to test branch
        run: |
          git config --global user.email "murali@realtekh.com"
          git config --global user.name "Murali"
          git add .
          git commit -m "Commit message"
          git push https://github.com/Muralirealtekh/Docker_jenkins.git HEAD:$TEST_BRANCH
        env:
          TEST_BRANCH: Test
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
